$schema: https://cdn.jsdelivr.net/gh/release-it/release-it/schema/release-it.json

git:
  addUntrackedFiles: true
  # commit: false
  commitArgs: --signoff
  commitMessage: "deploy(release-it): release v${version}"
  # requireBranch: main
  requireUpstream: true
  tagName: v${version}

hooks:
  after:bump: |
    node -e "require('fs').writeFileSync('messages/${version}.txt', process.argv[1])" -- "${changelog}"

# npx changelogen |
# tee messages/${version}.txt &&
# json -e "this['${version}']='messages/${version}.txt'" -f messages.json --in-place --output json-tab

# git add --all &&
# git commit --message="deploy(release-it): release ${version}" --signoff &&
# git push

kira: goddess

npm:
  publish: false

plugins:
  release-it-changelogen:
    disableVersion: true
    # output: messages/{{newVersion}}.txt
    # templates:
    #   commitMessage: "deploy(release-it): release {{newVersion}}"
    #   tagMessage: v{{newVersion}}

verbose: 2
