git:
  commitArgs: --signoff
  commitMessage: "deploy(release-it): release v${version}"
  pushArgs: --tags
  requireUpstream: false

npm:
  publish: false

plugins:
  "@release-it/conventional-changelog":
    infile: CHANGELOG.md
    preset:
      name: angular

#   "@release-it/keep-a-changelog":
#     filename: CHANGELOG.md
