git:
  commitArgs: --signoff
  commitMessage: "deploy(release-it): release v${version}"
  pushArgs: --tags
  requireUpstream: false

# github:
#   release: true

hooks:
  after:git:bump: "changelog -f - -u https:\/\/${repo.host}\/${repo.repository} |
                   tee messages\/${version}.txt | cat - CHANGELOG.md > temp
                   && mv temp CHANGELOG.md && sed -i '\/\\\"install\\\":
                   \\\"messages\\\/install\\.txt\\\"\/i\\\"${version}\\\":
                   \\\"messages\\\/${version}\\.txt\\\",' messages.json"

npm:
  publish: false

plugins:
  "@release-it/conventional-changelog":
    infile: CHANGELOG.md
    preset:
      name: angular
      types:
      - section: Deployments
        type: deploy

#   "@release-it/keep-a-changelog":
#     filename: CHANGELOG.md
